services:
  filebrowser:
    container_name: $GLOBAL_APP_NAME
    image: gtstef/filebrowser:stable
    user: 0:0
    restart: unless-stopped
    # environment:
      # - FILEBROWSER_ADMIN_PASSWORD=$GLOBAL_DEFAULT_PASSWORD
    networks:
      - appbox
    volumes:
      - $GLOBAL_STORAGE_PATH:/folder
      - $GLOBAL_APPDATA_PATH:/home/filebrowser/data
    ports:
      - $GLOBAL_IP:81:80
    configs:
      - source: config
        target: /home/filebrowser/data/config.yaml
    labels:
      - "traefik.enable=true"
      # --- HTTPS Router ---
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.rule=Host(`${GLOBAL_DOMAIN}`)"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.entrypoints=websecure"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.tls=true"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.tls.certresolver=letsencrypt"
      
      # --- HTTP Router
      - "traefik.http.routers.${GLOBAL_APP_NAME}-http.rule=Host(`${GLOBAL_DOMAIN}`)"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-http.entrypoints=web"
      
      # --- Service Definition
      - "traefik.http.services.${GLOBAL_APP_NAME}.loadbalancer.server.port=80"

configs:
  config:
    content: |
      server:
        cacheDir: /tmp/filebrowser
        sources:
          - path: /folder
            config:
              defaultEnabled: true




networks:
  appbox:
    name: appbox
    external: true