services:
  gitea:
    container_name: $GLOBAL_APP_NAME
    image: docker.gitea.com/gitea:1.27.3
    restart: always
    ports:
      - $GLOBAL_IP:24:24
      - $GLOBAL_IP:3000:3000
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/London

      # - GITEA__security__INSTALL_LOCK=true
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=$GITEA_DATABASE_PASSWORD

      - GITEA__server__DOMAIN=$GLOBAL_DOMAIN
      - GITEA__server__ROOT_URL=https://$GLOBAL_DOMAIN
      - GITEA__server__SSH_PORT=24
      - GITEA__server__SSH_LISTEN_PORT=24
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__NO_REPLY_ADDRESS=noreply.$GLOBAL_DOMAIN

      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
    networks:
      - gitea
      - appbox
    volumes:
      - $GLOBAL_APPDATA_PATH/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea-mysql
    labels:
      - "traefik.enable=true"
      # --- HTTPS Router ---
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.rule=Host(`${GLOBAL_DOMAIN}`)"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.entrypoints=websecure"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.tls=true"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.tls.certresolver=letsencrypt"
      
      # --- HTTP Router
      - "traefik.http.routers.${GLOBAL_APP_NAME}-http.rule=Host(`${GLOBAL_DOMAIN}`)"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-http.entrypoints=web"
      
      # --- Service Definition
      - "traefik.http.services.${GLOBAL_APP_NAME}.loadbalancer.server.port=3000"

  gitea-mysql:
    container_name: gitea-mysql
    image: docker.io/library/mysql:8
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=${GITEA_DATABASE_PASSWORD}
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - $GLOBAL_APPDATA_PATH/database:/var/lib/mysql



networks:
  appbox:
    name: appbox
    external: true
  gitea:
    name: gitea
    external: false