title: Gitea
description: Store all your git repositories.
icon_url: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/gitea.svg
environment_variable_templates:
  - label: "Gitea Database Password"
    key: "GITEA_DATABASE_PASSWORD"
    autoFill: true
    showOnFrontend: false