title: Gitea
description: Store all your git repositories.
icon_url: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/gitea.svg
environment_variable_templates:
  - label: "Database Password"
    key: "GITEA_DATABASE_PASSWORD"
    auto_fill: true
    show_on_frontend: false
  - label: "Root Database Password"
    key: "GITEA_DATABASE_PASSWORD_ROOT"
    auto_fill: true
    show_on_frontend: false