services:
  coredns:
    container_name: $GLOBAL_APP_NAME
    image: coredns/coredns:latest
    command: -conf /Corefile
    restart: unless-stopped
    networks:
      - appbox
    ports:
      - 53:53/tcp
      - 53:53/udp
    configs:
      - source: Corefile
        target: /Corefile

configs:
  Corefile:
    content: |
      appbox:53 {
        template ANY A {
          match "^(.*\.)?appbox\.$"
          answer "{{ .Name }} 60 IN A $IP_ADDRESS"
          fallthrough
        }

        hosts {
          $IP_ADDRESS appbox
        }
      }

      .:53 {
          forward . 172.30.0.100 1.1.1.1 8.8.8.8
          cache 30
          errors
          log
      }


networks:
  appbox:
    name: appbox
    external: true