services:
  jellyfin:
    container_name: $GLOBAL_APP_NAME
    image: jellyfin/jellyfin:latest
    hostname: $GLOBAL_APP_NAME
    restart: unless-stopped
    ports:
      - $GLOBAL_IP:8096:8096
    networks:
      - appbox
    volumes:
      - $GLOBAL_APPDATA_PATH/config:/config
      - $GLOBAL_APPDATA_PATH/cache:/cache
      - $GLOBAL_STORAGE_PATH/Media:/media
    labels:
      - "traefik.enable=true"
      # --- HTTPS Router ---
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.rule=Host(`${GLOBAL_DOMAIN}`)"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.entrypoints=websecure"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.tls=true"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-https.tls.certresolver=letsencrypt"
      
      # --- HTTP Router
      - "traefik.http.routers.${GLOBAL_APP_NAME}-http.rule=Host(`${GLOBAL_DOMAIN}`)"
      - "traefik.http.routers.${GLOBAL_APP_NAME}-http.entrypoints=web"
      
      # --- Service Definition
      - "traefik.http.services.${GLOBAL_APP_NAME}.loadbalancer.server.port=8096"


networks:
  appbox:
    name: appbox
    external: true